basic:
  data_path: "data/beijing-south , huai'an-air-quality.csv"
  env_path: '.env'
  city_id: 7397
  feature_group_name: "air_quality_feature_group"
  feature_group_version: 1

train:
  artifact_dir: "artifacts/"
  model_name: "XGBRegressor"
  src_dir: "src/"
  ffill_limit: 3
  lags: 5
  n_trials: 10
  direction: "minimize"
  study_name: "test"
