basic:
  data_path: "data/beijing-south , huai'an-air-quality.csv"
  env_path: '.env'
  city_id: 7397
  feature_group_name: "air_quality_feature_group"
  feature_group_description: "Air quality index data"
  prediction_group_name: "air_quality_prediction"
  prediction_group_description: "Air Quality Prediction"
  feature_group_version: 1

azure:
  resource_group: 'rg-airqualityforecast' #TODO: comments as explanations
  workspace: 'ml-airqualityforecast'
  environment: "airquality_env@latest"
  compute: "airquality-inference"
  inference_display_name: "air-quality-inference"
  inference_experiment_name: "air-quality-inference"
  feature_display_name: "air-quality-feature"
  feature_experiment_name: "air-quality-feature"
  vault_url: "https://mlairquakeyvaultc450882a.vault.azure.net/"

train:
  artifact_dir: "artifacts/"
  model_name: "XGBRegressor"
  src_dir: "src/"
  ffill_limit: 3
  lags: 5
  n_trials: 1
  direction: "minimize"
  study_name: "test"

inference:
  model_dir: 'model'
