display_name: pipeline_function_name
type: pipeline
jobs:
  feature:
    type: command
    inputs:
      config: config.yaml
    resources:
      instance_count: 1
    component:
      $schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
      name: feature_pipeline
      version: '2'
      display_name: Run feature pipeline
      type: command
      inputs:
        config:
          type: string
          optional: false
          default: config.yaml
      outputs:
        config:
          type: string
      command: python components/comp_api_feature_pipeline.py  --config config.yaml
      environment: azureml:/subscriptions/c47371d3-d4b1-40e4-9a49-ca581385557d/resourceGroups/rg-airqualityforecast/providers/Microsoft.MachineLearningServices/workspaces/ml-airqualityforecast/environments/airquality_env/versions/2
      code: azureml:/subscriptions/c47371d3-d4b1-40e4-9a49-ca581385557d/resourceGroups/rg-airqualityforecast/providers/Microsoft.MachineLearningServices/workspaces/ml-airqualityforecast/codes/ee391ca1-d66c-4921-bafa-38112bc77edc/versions/1
      resources:
        instance_count: 1
      creation_context:
        created_at: '2024-10-16T12:04:37.867597+00:00'
        created_by: Zsombor Teremy
        created_by_type: User
        last_modified_at: '2024-10-16T12:04:37.929688+00:00'
        last_modified_by: Zsombor Teremy
        last_modified_by_type: User
      id: /subscriptions/c47371d3-d4b1-40e4-9a49-ca581385557d/resourceGroups/rg-airqualityforecast/providers/Microsoft.MachineLearningServices/workspaces/ml-airqualityforecast/components/feature_pipeline/versions/2
      is_deterministic: true
  inference:
    type: command
    inputs:
      config:
        path: ${{parent.jobs.feature.outputs.config}}
    resources:
      instance_count: 1
    component:
      $schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
      name: inference_pipeline
      version: '2'
      display_name: Run inference pipeline
      type: command
      inputs:
        config:
          type: string
          optional: false
          default: config.yaml
      command: python components/comp_inference_pipeline.py  --config config.yaml
      environment: azureml:/subscriptions/c47371d3-d4b1-40e4-9a49-ca581385557d/resourceGroups/rg-airqualityforecast/providers/Microsoft.MachineLearningServices/workspaces/ml-airqualityforecast/environments/airquality_env/versions/2
      code: azureml:/subscriptions/c47371d3-d4b1-40e4-9a49-ca581385557d/resourceGroups/rg-airqualityforecast/providers/Microsoft.MachineLearningServices/workspaces/ml-airqualityforecast/codes/9caf3292-494e-4e48-a941-d8fa954fe4c6/versions/1
      resources:
        instance_count: 1
      creation_context:
        created_at: '2024-10-16T10:05:10.066506+00:00'
        created_by: Zsombor Teremy
        created_by_type: User
        last_modified_at: '2024-10-16T10:05:10.201310+00:00'
        last_modified_by: Zsombor Teremy
        last_modified_by_type: User
      id: /subscriptions/c47371d3-d4b1-40e4-9a49-ca581385557d/resourceGroups/rg-airqualityforecast/providers/Microsoft.MachineLearningServices/workspaces/ml-airqualityforecast/components/inference_pipeline/versions/2
      is_deterministic: true
