name: App CICD pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.10'
    - name: Update pip
      run: pip install -U pip

    - name: Install poetry
      run: pip install poetry==1.5.1

    - name: Install azure cli
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add -n ml

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install python packages
      run: |
        poetry install

    - name: Run code quality tests
      run: |
        poetry run isort --check src
        poetry run black src --check
        poetry run flake8 src

    - name: Run type tests
      run: |
        poetry run mypy src/

    - name: Run unit tests
      run: |
        poetry run pytest tests/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build docker image
      run: |
        docker build -t teremyz21/airquality_env .

    - name: push docker image
      run: |
        docker push teremyz21/airquality_env

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.10'

    - name: Install azure cli
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
        az extension add -n ml

    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: create environment in azure ml from docker image
      run: |
        az ml environment create --file airq-azure-environment.yaml --resource-group rg-airqualityforecast --workspace-name ml-airqualityforecast
